[package]
name = "aoc_2015"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timer = { path = "./timer" }
md5 = { path = "./md5" }
regex-lite = "0.1.5"
